package software.sava.anchor.programs.glam.staging.anchor.types;

import software.sava.core.borsh.Borsh;

public enum ShareClassFieldName implements Borsh.Enum {

  ISIN,
  ShareClassCurrency,
  AppliedSubscriptionFeeInFavourOfDistributor,
  AppliedSubscriptionFeeInFavourOfDistributorReferenceDate,
  CurrencyOfMinimalSubscription,
  FullShareClassName,
  HasPerformanceFee,
  HasSubscriptionFeeInFavourOfDistributor,
  InvestmentStatus,
  ManagementFeeApplied,
  ManagementFeeAppliedReferenceDate,
  ManagementFeeMaximum,
  MaximumSubscriptionFeeInFavourOfDistributor,
  MinimalInitialSubscriptionCategory,
  MinimalInitialSubscriptionInAmount,
  MinimalInitialSubscriptionInShares,
  MinimalSubsequentSubscriptionCategory,
  MinimalSubsequentSubscriptionInAmount,
  MinimalSubsequentSubscriptionInShares,
  MinimumSubscriptionFeeInFavourOfDistributor,
  ShareClassDistributionPolicy,
  ShareClassExtension,
  ShareClassLaunchDate,
  ShareClassLifecycle,
  SRRI,
  LaunchPrice,
  LaunchPriceCurrency,
  LaunchPriceDate,
  HasAppliedSubscriptionFeeInFavourOfFund,
  AppliedSubscriptionFeeInFavourOfFund,
  AppliedSubscriptionFeeInFavourOfFundReferenceDate,
  MaximumSubscriptionFeeInFavourOfFund,
  HasAppliedRedemptionFeeInFavourOfFund,
  AppliedRedemptionFeeInFavourOfFund,
  AppliedRedemptionFeeInFavourOfFundReferenceDate,
  MaximumRedemptionFeeInFavourOfFund,
  AppliedRedemptionFeeInFavourOfDistributor,
  AppliedRedemptionFeeInFavourOfDistributorReferenceDate,
  CurrencyOfMinimalOrMaximumRedemption,
  CutOffDateOffsetForRedemption,
  CutOffDateOffsetForSubscription,
  CutOffTimeForRedemption,
  CutOffTimeForSubscription,
  HasLockUpForRedemption,
  HasRedemptionFeeInFavourOfDistributor,
  IsValidISIN,
  LockUpComment,
  LockUpPeriodInDays,
  ManagementFeeMinimum,
  MaximalNumberOfPossibleDecimalsAmount,
  MaximalNumberOfPossibleDecimalsNAV,
  MaximalNumberOfPossibleDecimalsShares,
  MaximumInitialRedemptionInAmount,
  MaximumInitialRedemptionInShares,
  MaximumRedemptionFeeInFavourOfDistributor,
  MaximumSubsequentRedemptionInAmount,
  MaximumSubsequentRedemptionInShares,
  MinimalInitialRedemptionInAmount,
  MinimalInitialRedemptionInShares,
  MinimalRedemptionCategory,
  MinimalSubsequentRedemptionInAmount,
  MinimalSubsequentRedemptionInShares,
  MinimumRedemptionFeeInFavourOfDistributor,
  MinimumRedemptionFeeInFavourOfFund,
  MinimumSubscriptionFeeInFavourOfFund,
  PerformanceFeeMinimum,
  RoundingMethodForPrices,
  RoundingMethodForRedemptionInAmount,
  RoundingMethodForRedemptionInShares,
  RoundingMethodForSubscriptionInAmount,
  RoundingMethodForSubscriptionInShares,
  ShareClassDividendType,
  CUSIP,
  Valor,
  FundId,
  ImageUri;

  public static ShareClassFieldName read(final byte[] _data, final int offset) {
    return Borsh.read(ShareClassFieldName.values(), _data, offset);
  }
}