module software.sava.anchor_programs {
  exports software.sava.anchor.programs._commons;
  exports software.sava.anchor.programs.chainlink.ocr2.anchor.types;
  exports software.sava.anchor.programs.chainlink.ocr2.anchor;
  exports software.sava.anchor.programs.chainlink.store.anchor.types;
  exports software.sava.anchor.programs.chainlink.store.anchor;
  exports software.sava.anchor.programs.chainlink.store;
  exports software.sava.anchor.programs.flash.perpetuals.anchor.types;
  exports software.sava.anchor.programs.flash.perpetuals.anchor;
  exports software.sava.anchor.programs.jito.tip_distribution.anchor.types;
  exports software.sava.anchor.programs.jito.tip_distribution.anchor;
  exports software.sava.anchor.programs.jito.tip_router.anchor.types;
  exports software.sava.anchor.programs.jito.tip_router.anchor;
  exports software.sava.anchor.programs.jupiter.dca.anchor.types;
  exports software.sava.anchor.programs.jupiter.dca.anchor;
  exports software.sava.anchor.programs.jupiter.limit.anchor.types;
  exports software.sava.anchor.programs.jupiter.limit.anchor;
  exports software.sava.anchor.programs.loopscale.anchor.types;
  exports software.sava.anchor.programs.loopscale.anchor;
  exports software.sava.anchor.programs.marginfi.v2.anchor.types;
  exports software.sava.anchor.programs.marginfi.v2.anchor;
  exports software.sava.anchor.programs.metadao.amm.anchor.types;
  exports software.sava.anchor.programs.metadao.amm.anchor;
  exports software.sava.anchor.programs.metadao.autocrat.anchor.types;
  exports software.sava.anchor.programs.metadao.autocrat.anchor;
  exports software.sava.anchor.programs.metadao.conditional_vault.anchor.types;
  exports software.sava.anchor.programs.metadao.conditional_vault.anchor;
  exports software.sava.anchor.programs.metadao.launchpad.anchor.types;
  exports software.sava.anchor.programs.metadao.launchpad.anchor;
  exports software.sava.anchor.programs.moonshot.anchor.types;
  exports software.sava.anchor.programs.moonshot.anchor;
  exports software.sava.anchor.programs.raydium.launchpad.anchor.types;
  exports software.sava.anchor.programs.raydium.launchpad.anchor;
  requires java.base;
  requires java.net.http;
  requires transitive software.sava.core;
  requires transitive software.sava.rpc;
}
