package software.sava.anchor.programs.drift;

public enum DriftProduct {

  APT_PERP("APT-PERP"),
  ARB_PERP("ARB-PERP"),
  AVAX_PERP("AVAX-PERP"),
  BNB_PERP("BNB-PERP"),
  BREAKPOINT_IGGYERIC_BET("BREAKPOINT-IGGYERIC-BET"),
  BTC_PERP("BTC-PERP"),
  CLOUD_PERP("CLOUD-PERP"),
  DBR_PERP("DBR-PERP"),
  DEMOCRATS_WIN_MICHIGAN_BET("DEMOCRATS-WIN-MICHIGAN-BET"),
  DOGE_PERP("DOGE-PERP"),
  DRIFT_PERP("DRIFT-PERP"),
  DYM_PERP("DYM-PERP"),
  ETH_PERP("ETH-PERP"),
  FED_CUT_50_SEPT_2024_BET("FED-CUT-50-SEPT-2024-BET"),
  HNT_PERP("HNT-PERP"),
  INJ_PERP("INJ-PERP"),
  IO_PERP("IO-PERP"),
  JTO_PERP("JTO-PERP"),
  JUP_PERP("JUP-PERP"),
  KAMALA_POPULAR_VOTE_2024_BET("KAMALA-POPULAR-VOTE-2024-BET"),
  KAMALA_POPULAR_VOTE_2024_PREDICT("KAMALA-POPULAR-VOTE-2024-PREDICT"),
  KMNO_PERP("KMNO-PERP"),
  LANDO_F1_SGP_WIN_BET("LANDO-F1-SGP-WIN-BET"),
  LINK_PERP("LINK-PERP"),
  LNDO_WIN_F1_24_US_GP_BET("LNDO-WIN-F1-24-US-GP-BET"),
  MATIC_PERP("MATIC-PERP"),
  MICHI_PERP("MICHI-PERP"),
  MOODENG_PERP("MOODENG-PERP"),
  MOTHER_PERP("MOTHER-PERP"),
  OP_PERP("OP-PERP"),
  POPCAT_PERP("POPCAT-PERP"),
  PYTH_PERP("PYTH-PERP"),
  RENDER_PERP("RENDER-PERP"),
  REPUBLICAN_POPULAR_AND_WIN_BET("REPUBLICAN-POPULAR-AND-WIN-BET"),
  RLB_PERP("RLB-PERP"),
  SEI_PERP("SEI-PERP"),
  SOL_PERP("SOL-PERP"),
  SUI_PERP("SUI-PERP"),
  TAO_PERP("TAO-PERP"),
  TIA_PERP("TIA-PERP"),
  TNSR_PERP("TNSR-PERP"),
  TON_PERP("TON-PERP"),
  TRUMP_WIN_2024_BET("TRUMP-WIN-2024-BET"),
  TRUMP_WIN_2024_PREDICT("TRUMP-WIN-2024-PREDICT"),
  VRSTPN_WIN_F1_24_DRVRS_CHMP_BET("VRSTPN-WIN-F1-24-DRVRS-CHMP-BET"),
  WARWICK_FIGHT_WIN_BET("WARWICK-FIGHT-WIN-BET"),
  WIF_PERP("WIF-PERP"),
  WLF_5B_1W_BET("WLF-5B-1W-BET"),
  W_PERP("W-PERP"),
  XRP_PERP("XRP-PERP"),
  ZEX_PERP("ZEX-PERP"),
  _1KMEW_PERP("1KMEW-PERP"),
  _1KWEN_PERP("1KWEN-PERP"),
  _1MBONK_PERP("1MBONK-PERP"),
  _1MPEPE_PERP("1MPEPE-PERP");

  private final String symbol;

  DriftProduct(final String symbol) {
    this.symbol = symbol;
  }

  public String symbol() {
    return symbol;
  }
}
